### PR TITLE
@ iorad/teracy-dev-entry#34 | update id

### PR DESCRIPTION
**Pull request by datphan**

### CODE REVIEW

**Comment by hoatle** [comment]
this change will not work on teracy-dev-essential v0.1.0 (no backward compatible). We must:
- support the backward compabilitity (great) by using processor to dynamically set the right _id basing on the current teracy-dev-essential version
- or require teracy-dev-essential >= v0.2.0 (ok) on https://github.com/teracyhq-incubator/teracy-dev-v05-compat/blob/develop/manifest.yaml

**Review by hoatle — CHANGES_REQUESTED** [review]
@datphan pls check my comments

**Comment by datphan** [comment]
@hoatle I've update it, pls check again

**Review by hoatle — APPROVED** [review]
LGTM

**Pull request merged**
